theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
layout: page
title: "CatNur's homepage"
description: Hello World
permalink: https://catsnut.github.io/about/contact
